---
- hosts: all
  gather_facts: false
  tasks:
  - shell: hostname
    register: r
  - debug: var=r.stdout

  - debug: var=ansible_playbook_python
  - debug: var=ansible_connection
  - debug: var=ansible_python_interpreter
  - debug: var=hostvars[inventory_hostname].ansible_connection
  - debug: var=hostvars[inventory_hostname].ansible_python_interpreter
  - debug: var=ansible_os_family
  - debug: var=ansible_connection
  - debug: var=ansible_system
  - debug: var=ansible_architecture
