---

- name: Dockerに必要なパッケージを入れる
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes
    cache_valid_time: 3600

- name: DockerのGPGキーを追加
  become: yes
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present #absentで削除
  register: already_registered_docker_gpg_key

- name: Configure Docker's APT repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    update_cache: true

- name: Docker CE のインストール
  become: yes
  apt:
    name: docker-ce
    update_cache: yes

- name: dockerグループにvagrant userを追加
  become: yes
  user:
    name: vagrant
    groups: docker
